name: CI_Actions

on:
  push:
    branches: 
      - main
      
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3
      - name: install libraries
        run: pip install pymystem3
      - name: run programm
        run: python main.py
        
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
